# Generated by Django 5.2.6 on 2025-09-25 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('status_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'booking_status',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('hourly_rate_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_rate_snapshot', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('availability', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='facilities.availability')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='facilities.court')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bookings.bookingstatus')),
            ],
            options={
                'db_table': 'bookings',
                'indexes': [models.Index(fields=['user', 'created_at'], name='idx_bookings_user_created_at')],
                'constraints': [models.UniqueConstraint(fields=('court', 'start_time'), name='unique_court_booking_time')],
            },
        ),
    ]
