# Generated by Django 5.2.5 on 2025-10-18 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('facilities', '0007_facility_is_suspended'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryReservation',
            fields=[
                ('reservation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'temporary_reservations',
            },
        ),
        migrations.CreateModel(
            name='ReservationSlot',
            fields=[
                ('reservation_slot_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.availability')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='bookings.temporaryreservation')),
            ],
            options={
                'db_table': 'reservation_slots',
            },
        ),
        migrations.AddIndex(
            model_name='temporaryreservation',
            index=models.Index(fields=['user', 'expires_at'], name='idx_temp_res_user_expires'),
        ),
        migrations.AddIndex(
            model_name='temporaryreservation',
            index=models.Index(fields=['expires_at'], name='idx_temp_res_expires'),
        ),
        migrations.AddIndex(
            model_name='reservationslot',
            index=models.Index(fields=['availability'], name='idx_res_slot_availability'),
        ),
        migrations.AlterUniqueTogether(
            name='reservationslot',
            unique_together={('reservation', 'availability')},
        ),
    ]
