# Generated by Django 5.2.5 on 2025-10-19 04:51

from django.db import migrations


def populate_booking_statuses(apps, schema_editor):
    """Populate BookingStatus table with required statuses"""
    BookingStatus = apps.get_model('bookings', 'BookingStatus')

    statuses = [
        'pending_payment',
        'confirmed',
        'cancelled',
        'completed',
        'no_show'
    ]

    for status_name in statuses:
        BookingStatus.objects.get_or_create(status_name=status_name)


def reverse_populate_booking_statuses(apps, schema_editor):
    """Remove booking statuses on migration rollback"""
    BookingStatus = apps.get_model('bookings', 'BookingStatus')
    BookingStatus.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_temporaryreservation_reservationslot_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_booking_statuses, reverse_populate_booking_statuses),
    ]
