# Generated by Django 5.2.6 on 2025-09-25 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('action_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action_name', models.CharField(max_length=255)),
                ('resource_type', models.CharField(max_length=255)),
                ('resource_id', models.BigIntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('financial_impact', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='admin_actions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_action_log',
            },
        ),
        migrations.CreateModel(
            name='FacilityRequest',
            fields=[
                ('request_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('motivation', models.TextField()),
                ('facility_name', models.CharField(max_length=255)),
                ('facility_address', models.CharField(max_length=500)),
                ('contact_phone', models.CharField(max_length=32)),
                ('proposed_timezone', models.CharField(max_length=50)),
                ('proposed_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('proposed_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('court_count', models.IntegerField(blank=True, null=True)),
                ('operating_hours', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_facility_requests', to=settings.AUTH_USER_MODEL)),
                ('approved_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.facility')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'facility_requests',
            },
        ),
        migrations.CreateModel(
            name='FacilityRequestSportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindashboard.facilityrequest')),
                ('sport_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='facilities.sporttype')),
            ],
            options={
                'db_table': 'facility_request_sport_types',
            },
        ),
        migrations.CreateModel(
            name='ManagerRequest',
            fields=[
                ('request_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('facility_name', models.CharField(max_length=255)),
                ('facility_address', models.CharField(max_length=500)),
                ('contact_phone', models.CharField(max_length=32)),
                ('proposed_timezone', models.CharField(max_length=50)),
                ('proposed_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('proposed_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('court_count', models.IntegerField(blank=True, null=True)),
                ('operating_hours', models.JSONField(blank=True, null=True)),
                ('business_experience', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_manager_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'manager_requests',
            },
        ),
        migrations.CreateModel(
            name='ManagerRequestSportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindashboard.managerrequest')),
                ('sport_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='facilities.sporttype')),
            ],
            options={
                'db_table': 'manager_request_sport_types',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.BigIntegerField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('reporter_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_by', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('activity_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=64)),
                ('resource_type', models.CharField(blank=True, max_length=50, null=True)),
                ('resource_id', models.BigIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_log',
                'indexes': [models.Index(fields=['user', 'created_at'], name='idx_activity_user_time'), models.Index(fields=['action'], name='idx_activity_action')],
            },
        ),
        migrations.AddIndex(
            model_name='facilityrequest',
            index=models.Index(fields=['submitted_by'], name='idx_facreq_submitter'),
        ),
        migrations.AddIndex(
            model_name='facilityrequest',
            index=models.Index(fields=['status', 'created_at'], name='idx_facreq_status'),
        ),
        migrations.AddIndex(
            model_name='facilityrequest',
            index=models.Index(fields=['facility_name', 'facility_address'], name='idx_facreq_facility_name_addr'),
        ),
        migrations.AddConstraint(
            model_name='facilityrequest',
            constraint=models.UniqueConstraint(fields=('facility_name', 'facility_address', 'submitted_by'), name='ux_facreq_submitter_facility_key'),
        ),
        migrations.AddConstraint(
            model_name='facilityrequestsporttype',
            constraint=models.UniqueConstraint(fields=('request', 'sport_type'), name='unique_facility_request_sport_type'),
        ),
        migrations.AddIndex(
            model_name='managerrequest',
            index=models.Index(fields=['user'], name='idx_mgr_req_user'),
        ),
        migrations.AddConstraint(
            model_name='managerrequest',
            constraint=models.UniqueConstraint(fields=('facility_name', 'facility_address', 'user'), name='ux_mgr_req_user_facility_key'),
        ),
        migrations.AddConstraint(
            model_name='managerrequestsporttype',
            constraint=models.UniqueConstraint(fields=('request', 'sport_type'), name='unique_request_sport_type'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['resource_type', 'resource_id'], name='idx_reports_resource'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='idx_reports_status'),
        ),
    ]
