# Generated by Django 5.2.5 on 2025-10-18 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0002_commissionadjustment_facilitysuspension_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactionlog',
            name='reason',
            field=models.TextField(),
        ),
    ]
