# Generated by Django 5.2.6 on 2025-09-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='commission_rate',
            field=models.DecimalField(decimal_places=4, default='0.1000', help_text='Commission rate as decimal (e.g., 0.10 for 10%)', max_digits=5),
        ),
    ]
