# Generated by Django 5.2.6 on 2025-10-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_alter_facility_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='image',
            field=models.ImageField(blank=True, help_text='Facility image', null=True, upload_to='facilities/'),
        ),
    ]
