# Generated by Django 5.2.6 on 2025-10-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0005_court_check_hourly_rate_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='availability_start_date',
            field=models.DateField(blank=True, help_text='Date from which availability is generated', null=True),
        ),
        migrations.AddField(
            model_name='court',
            name='closing_time',
            field=models.TimeField(blank=True, help_text='Daily closing time (e.g., 22:00)', null=True),
        ),
        migrations.AddField(
            model_name='court',
            name='opening_time',
            field=models.TimeField(blank=True, help_text='Daily opening time (e.g., 06:00)', null=True),
        ),
    ]
