# Generated by Django 5.2.6 on 2025-10-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0009_facility_court_count_facility_operating_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='image_url',
            field=models.CharField(blank=True, help_text='Court image URL (external link or static asset)', max_length=500, null=True),
        ),
    ]
