# Generated by Django 5.2.6 on 2025-10-23 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0010_court_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='court',
            name='image_url',
        ),
    ]
