# Generated by Django 5.2.5 on 2025-10-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_manager_is_suspended_manager_idx_manager_suspended'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_enabled',
            field=models.BooleanField(default=False, help_text='Whether MFA (OTP via email) is enabled for this user'),
        ),
    ]
