# Generated by Django 5.2.6 on 2025-10-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='is_suspended',
            field=models.BooleanField(default=False, help_text='Whether manager is currently suspended'),
        ),
        migrations.AddIndex(
            model_name='manager',
            index=models.Index(fields=['is_suspended'], name='idx_manager_suspended'),
        ),
    ]
