# Generated by Django 5.2.6 on 2025-10-18 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0001_initial'),
        ('bookings', '0001_initial'),
        ('facilities', '0007_facility_is_suspended'),
        ('users', '0002_manager_is_suspended_manager_idx_manager_suspended'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionAdjustment',
            fields=[
                ('adjustment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('old_rate', models.DecimalField(decimal_places=4, help_text='Previous commission rate (e.g., 0.1000 for 10%)', max_digits=5)),
                ('new_rate', models.DecimalField(decimal_places=4, help_text='New commission rate (e.g., 0.1500 for 15%)', max_digits=5)),
                ('reason', models.TextField()),
                ('effective_date', models.DateTimeField(help_text='When this rate takes effect')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'commission_adjustments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacilitySuspension',
            fields=[
                ('suspension_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('duration_days', models.IntegerField(blank=True, help_text='Suspension duration in days. Null for indefinite.', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('lifted', 'Lifted')], default='active', max_length=20)),
                ('suspended_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Automatically calculated based on duration_days', null=True)),
                ('unsuspended_at', models.DateTimeField(blank=True, null=True)),
                ('unsuspension_reason', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'facility_suspensions',
                'ordering': ['-suspended_at'],
            },
        ),
        migrations.CreateModel(
            name='ManagerSuspension',
            fields=[
                ('suspension_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('duration_days', models.IntegerField(blank=True, help_text='Suspension duration in days. Null for indefinite.', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('lifted', 'Lifted')], default='active', max_length=20)),
                ('suspended_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Automatically calculated based on duration_days', null=True)),
                ('unsuspended_at', models.DateTimeField(blank=True, null=True)),
                ('unsuspension_reason', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'manager_suspensions',
                'ordering': ['-suspended_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('request_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, help_text='Refund amount requested', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processed', 'Processed')], default='pending', max_length=20)),
                ('review_reason', models.TextField(blank=True, help_text='Admin reason for approval/rejection', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('refund_transaction_id', models.CharField(blank=True, help_text='Payment provider refund ID', max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'refund_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('spam', 'Spam'), ('fraud', 'Fraud'), ('harassment', 'Harassment'), ('inappropriate', 'Inappropriate Content'), ('policy_violation', 'Policy Violation'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['severity', 'created_at'], name='idx_reports_severity'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['assigned_to'], name='idx_reports_assigned'),
        ),
        migrations.AddField(
            model_name='commissionadjustment',
            name='adjusted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='commission_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commissionadjustment',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_adjustments', to='facilities.facility'),
        ),
        migrations.AddField(
            model_name='facilitysuspension',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspensions', to='facilities.facility'),
        ),
        migrations.AddField(
            model_name='facilitysuspension',
            name='suspended_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='facility_suspensions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facilitysuspension',
            name='unsuspended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_suspensions_lifted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='managersuspension',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspensions', to='users.manager'),
        ),
        migrations.AddField(
            model_name='managersuspension',
            name='suspended_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='manager_suspensions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='managersuspension',
            name='unsuspended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_suspensions_lifted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='commissionadjustment',
            index=models.Index(fields=['facility', 'effective_date'], name='idx_comm_adj_facility'),
        ),
        migrations.AddIndex(
            model_name='commissionadjustment',
            index=models.Index(fields=['adjusted_by'], name='idx_comm_adj_admin'),
        ),
        migrations.AddIndex(
            model_name='facilitysuspension',
            index=models.Index(fields=['facility', 'status'], name='idx_fac_susp_facility_status'),
        ),
        migrations.AddIndex(
            model_name='facilitysuspension',
            index=models.Index(fields=['suspended_at'], name='idx_fac_susp_created'),
        ),
        migrations.AddIndex(
            model_name='facilitysuspension',
            index=models.Index(fields=['expires_at'], name='idx_fac_susp_expires'),
        ),
        migrations.AddIndex(
            model_name='managersuspension',
            index=models.Index(fields=['manager', 'status'], name='idx_mgr_susp_manager_status'),
        ),
        migrations.AddIndex(
            model_name='managersuspension',
            index=models.Index(fields=['suspended_at'], name='idx_mgr_susp_created'),
        ),
        migrations.AddIndex(
            model_name='managersuspension',
            index=models.Index(fields=['expires_at'], name='idx_mgr_susp_expires'),
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['booking'], name='idx_refund_booking'),
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['requested_by'], name='idx_refund_requester'),
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['status', 'created_at'], name='idx_refund_status'),
        ),
    ]
