# Generated by Django 5.2.6 on 2025-10-23 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0003_alter_adminactionlog_reason'),
        ('facilities', '0009_facility_court_count_facility_operating_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerrequest',
            name='approved_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_request', to='facilities.facility'),
        ),
    ]
