# Generated by Django 5.2.6 on 2025-09-25 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SportType',
            fields=[
                ('sport_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sport_name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sport_types',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('facility_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('facility_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('timezone', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('approval_status', models.CharField(default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_facilities', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='users.manager')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_facilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'facilities',
            },
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('court_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility')),
                ('sport_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='facilities.sporttype')),
            ],
            options={
                'db_table': 'courts',
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('availability_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_available', models.BooleanField()),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.court')),
            ],
            options={
                'db_table': 'availabilities',
                'constraints': [models.UniqueConstraint(fields=('court', 'start_time'), name='unique_court_start_time'), models.UniqueConstraint(fields=('availability_id', 'court', 'start_time', 'end_time'), name='unique_availability_composite')],
            },
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['latitude', 'longitude'], name='idx_facilities_latlon'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['facility_name', 'address'], name='idx_fac_dupe_guard'),
        ),
        migrations.AddConstraint(
            model_name='facility',
            constraint=models.UniqueConstraint(condition=models.Q(('manager__isnull', False)), fields=('manager', 'facility_name'), name='ux_facilities_manager_name_nonnull'),
        ),
        migrations.AddConstraint(
            model_name='court',
            constraint=models.UniqueConstraint(fields=('facility', 'name'), name='unique_court_per_facility'),
        ),
    ]
