# Generated by Django 5.2.6 on 2025-10-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_facility_commission_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='timezone',
            field=models.CharField(choices=[('Australia/Sydney', 'Sydney (NSW, ACT)'), ('Australia/Melbourne', 'Melbourne (VIC)'), ('Australia/Brisbane', 'Brisbane (QLD)'), ('Australia/Adelaide', 'Adelaide (SA)'), ('Australia/Perth', 'Perth (WA)'), ('Australia/Hobart', 'Hobart (TAS)'), ('Australia/Darwin', 'Darwin (NT)')], default='Australia/Sydney', max_length=50),
        ),
    ]
