# Generated by Django 5.2.6 on 2025-10-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_facility_image'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='court',
            constraint=models.CheckConstraint(condition=models.Q(('hourly_rate__gte', 10), ('hourly_rate__lte', 200)), name='check_hourly_rate_range'),
        ),
    ]
