# Generated by Django 5.2.6 on 2025-10-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_court_availability_start_date_court_closing_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='is_suspended',
            field=models.BooleanField(default=False, help_text='Whether facility is currently suspended by admin'),
        ),
    ]
