# Generated by Django 5.2.6 on 2025-10-21 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_populate_booking_statuses'),
        ('facilities', '0007_facility_is_suspended'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityReview',
            fields=[
                ('review_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(help_text='Rating from 1-5 stars')),
                ('comment', models.TextField(blank=True, help_text='Optional review comment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='facilities.facility')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'facility_reviews',
                'indexes': [models.Index(fields=['facility', 'created_at'], name='idx_reviews_facility_created'), models.Index(fields=['user', 'created_at'], name='idx_reviews_user_created')],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='check_rating_range'), models.UniqueConstraint(fields=('user', 'booking'), name='unique_user_booking_review')],
            },
        ),
    ]
