# Generated by Django 5.2.6 on 2025-10-23 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0008_facilityreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='court_count',
            field=models.IntegerField(blank=True, help_text='Number of courts at this facility', null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='operating_hours',
            field=models.JSONField(blank=True, help_text="Operating hours as JSON (e.g., {'Monday': '9am-5pm'})", null=True),
        ),
        migrations.CreateModel(
            name='FacilitySportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_types', to='facilities.facility')),
                ('sport_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='facilities.sporttype')),
            ],
            options={
                'db_table': 'facility_sport_types',
                'constraints': [models.UniqueConstraint(fields=('facility', 'sport_type'), name='unique_facility_sport_type')],
            },
        ),
    ]
