# Generated by Django 5.2.5 on 2025-10-19 04:52

from django.db import migrations


def populate_payment_statuses(apps, schema_editor):
    """Populate PaymentStatus table with required statuses"""
    PaymentStatus = apps.get_model('payments', 'PaymentStatus')

    statuses = [
        'pending',
        'processing',
        'completed',
        'failed',
        'cancelled',
        'refunded'
    ]

    for status_name in statuses:
        PaymentStatus.objects.get_or_create(status_name=status_name)


def reverse_populate_payment_statuses(apps, schema_editor):
    """Remove payment statuses on migration rollback"""
    PaymentStatus = apps.get_model('payments', 'PaymentStatus')
    PaymentStatus.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_payment_statuses, reverse_populate_payment_statuses),
    ]
