# Generated by Django 5.2.5 on 2025-10-18 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='6-digit OTP code', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When this OTP expires')),
                ('is_used', models.BooleanField(default=False, help_text='Whether this OTP has been used')),
                ('purpose', models.CharField(default='admin_reauth', help_text='What this OTP is for (admin_reauth, login, etc.)', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_otp_codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='auth_otp_co_user_id_4942d0_idx'), models.Index(fields=['code', 'is_used'], name='auth_otp_co_code_366bfc_idx')],
            },
        ),
    ]
